general:
  random_seed: 42
  
data:
  dataset_folder: "../../../../filer-5/user/plutenko/nmr_data/wheet_slice_rotation/rotation_dataset"
  dataframe_folder: "../../../../filer-5/user/plutenko/nmr_data/wheet_slice_rotation/data_full.csv"
  saved_models_folder: "saved_models"

  
train:
  batch_size: 32
  num_workers: 8
  saving_milestone: 2
  lr: 0.0002
  up_lr: 0.0008
  num_epochs: 30
  steps_divider: 15
  notebook: False
  optimizer: "MSELoss"
  losses_file: "losses.csv"
  lr_rates_file: "lr_rates.csv"
  savefig_png: "rate.png"
  savefig_pdf: "rate.pdf" 
  savefig_png2: "rate2.png"
  savefig_pdf2: "rate2.pdf"

model:
  in_channels: 1
  outputs: 2
  dimensions: 2
  n_blocks: [2,2,2,2]
  channels: [16, 32, 64, 128]

restore:
  model_name: 'saved_models/best_model.pt'

evaluation:
  savefig_png: "sorted_predictions.png"
  savefig_pdf: "sorted_predictions.pdf" 
